# Generated by Django 5.0.3 on 2024-03-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='print',
            new_name='price',
        ),
    ]
